In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Club_Stats.csv")
domestic_league= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_leagues.csv")
domestic_cup= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_cups.csv")
international_cups = pd.read_csv(r"C:\Users\salma\Downloads\International_cups.csv")
national_team = pd.read_csv(r"C:\Users\salma\Downloads\National_Team.csv")

#shooting

shooting_club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Shooting_Standard_Stats.csv")
shooting_domestic_league = pd.read_csv(r"C:\Users\salma\Downloads\League_Shooting_Standard_Stats_and_Summary.csv")
shooting_domestic_cup = pd.read_csv(r"C:\Users\salma\Downloads\Domestic_Cups_Shooting_Standard_Stats_and_Summary.csv")
shooting_international_cups = pd.read_csv(r"C:\Users\salma\Downloads\European_International_Cups_Shooting_Standard_Stats.csv")
shooting_national_team = pd.read_csv(r"C:\Users\salma\Downloads\International_England_Shooting_Standard_Stats.csv")

In [3]:
club_standard_stats = club_standard_stats.copy()
domestic_league = domestic_league.copy()
domestic_cup = domestic_cup.copy()
international_cups = international_cups.copy()
national_team = national_team.copy()

club_standard_stats["Competition_Type"] = "Club"
domestic_league["Competition_Type"] = "Domestic League"
domestic_cup["Competition_Type"] = "Domestic Cup"
international_cups["Competition_Type"] = "International Cup"
national_team["Competition_Type"] = "National Team"

In [4]:
shooting_club_standard_stats["Competition_Type"] = "Club"
shooting_domestic_league["Competition_Type"] = "Domestic League"
shooting_domestic_cup["Competition_Type"] = "Domestic Cup"
shooting_international_cups["Competition_Type"] = "International Cup"
shooting_national_team["Competition_Type"] = "National Team"

In [5]:
standard_stats = pd.concat(
    [
        club_standard_stats,
        domestic_league,
        domestic_cup,
        international_cups,
        national_team
    ],
    ignore_index=True
)

In [6]:
standard_stats.shape

(62, 24)

In [7]:
standard_stats.head()

,Season,Age,Squad,Country,Comp,LgRank,MP,Starts,Min,90s,...,PK,PKatt,CrdY,CrdR,Gls_90,Ast_90,G+A_90,G-PK_90,G+A-PK_90,Competition_Type
0,2019-2020,16.0,Birmingham City,ENG,2. Championship,20th,41.0,32.0,2694.0,29.9,...,0.0,0.0,7.0,0.0,0.13,0.07,0.20,0.13,0.20,Club
1,2020-2021,17.0,Dortmund,GER,1. Bundesliga,3rd,29.0,19.0,1697.0,18.9,...,0.0,0.0,6.0,1.0,0.05,0.16,0.21,0.05,0.21,Club
2,2021-2022,18.0,Dortmund,GER,1. Bundesliga,2nd,32.0,32.0,2790.0,31.0,...,0.0,0.0,9.0,0.0,0.10,0.26,0.35,0.10,0.35,Club
3,2022-2023,19.0,Dortmund,GER,1. Bundesliga,2nd,31.0,30.0,2691.0,29.9,...,1.0,0.0,8.0,1.0,0.27,0.13,0.40,0.23,0.37,Club
4,2023-2024,20.0,Real Madrid,ESP,1. La Liga,1st,28.0,27.0,2315.0,25.7,...,1.0,1.0,5.0,1.0,0.74,0.23,0.97,0.70,0.93,Club

In [8]:
shooting = pd.concat(
    [
        shooting_club_standard_stats,
        shooting_domestic_league,
        shooting_domestic_cup,
        shooting_international_cups,
        shooting_national_team
    ],
    ignore_index=True
)

In [9]:
shooting.shape

(78, 18)

In [10]:
shooting["Competition_Type"].value_counts()

Competition_Type
Club                 31
National Team        16
Domestic Cup         13
International Cup    10
Domestic League       8
Name: count, dtype: int64

In [11]:
standard_stats[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

       Season            Squad             Comp   Competition_Type
0   2019-2020  Birmingham City  2. Championship               Club
16  2019-2020  Birmingham City          EFL Cup       Domestic Cup
17  2019-2020  Birmingham City           FA Cup       Domestic Cup
8   2019-2020  Birmingham City  2. Championship    Domestic League
46       2020          England   Friendlies (M)      National Team
..        ...              ...              ...                ...
41        NaN              NaN              NaN  International Cup
42        NaN              NaN              NaN  International Cup
43        NaN              NaN              NaN  International Cup
44        NaN              NaN              NaN  International Cup
45        NaN              NaN              NaN  International Cup

[62 rows x 4 columns]

In [12]:
shooting[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

       Season            Squad             Comp   Competition_Type
0   2019-2020  Birmingham City  2. Championship               Club
1   2019-2020  Birmingham City          EFL Cup               Club
2   2019-2020  Birmingham City           FA Cup               Club
39  2019-2020  Birmingham City          EFL Cup       Domestic Cup
40  2019-2020  Birmingham City           FA Cup       Domestic Cup
..        ...              ...              ...                ...
77       2026          England   Friendlies (M)      National Team
29  2026-2027      Real Madrid  1. Champions Lg               Club
30  2026-2027      Real Madrid       1. La Liga               Club
38  2026-2027      Real Madrid       1. La Liga    Domestic League
61  2026-2027      Real Madrid  1. Champions Lg  International Cup

[78 rows x 4 columns]

In [13]:
standard_stats.groupby(
    ["Season", "Competition_Type"]
).size()

Season     Competition_Type
2019-2020  Club                 1
           Domestic Cup         2
           Domestic League      1
2020       National Team        1
2020-2021  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
           National Team        1
2021       National Team        2
2021-2022  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    2
2022       National Team        3
2022-2023  Club                 1
           Domestic Cup         1
           Domestic League      1
           International Cup    1
           National Team        1
2023       National Team        1
2023-2024  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2024       National Team        2
2024-2025  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    2
           National Team        1
2025       International Cup    1
           National Team        1
2025-2026  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2026       National Team        3
2026-2027  Club                 1
           Domestic League      1
           International Cup    1
dtype: int64

In [14]:
shooting.groupby(
    ["Season", "Competition_Type"]
).size()

Season     Competition_Type
2019-2020  Club                 3
           Domestic Cup         2
           Domestic League      1
2020       National Team        1
2020-2021  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2021       National Team        2
2021-2022  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
2022       National Team        3
2022-2023  Club                 3
           Domestic Cup         1
           Domestic League      1
           International Cup    1
           National Team        1
2023       National Team        1
2023-2024  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2024       National Team        3
2024-2025  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
           National Team        1
2025       Club                 1
           International Cup    1
           National Team        1
2025-2026  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2026       National Team        3
2026-2027  Club                 2
           Domestic League      1
           International Cup    1
dtype: int64

In [15]:
standard_stats.isna().sum()

Season               7
Age                  7
Squad                7
Country             33
Comp                 7
LgRank              17
MP                   7
Starts               7
Min                  8
90s                  8
Gls                  7
Ast                  8
G+A                  8
G-PK                 8
PK                   8
PKatt                8
CrdY                 8
CrdR                 8
Gls_90               8
Ast_90               8
G+A_90               8
G-PK_90              8
G+A-PK_90            8
Competition_Type     0
dtype: int64

In [16]:
standard_stats.dtypes

Season                  str
Age                 float64
Squad                   str
Country                 str
Comp                    str
LgRank                  str
MP                  float64
Starts              float64
Min                 float64
90s                 float64
Gls                  object
Ast                 float64
G+A                 float64
G-PK                float64
PK                  float64
PKatt               float64
CrdY                float64
CrdR                float64
Gls_90              float64
Ast_90              float64
G+A_90              float64
G-PK_90             float64
G+A-PK_90           float64
Competition_Type        str
dtype: object

In [17]:
shooting.dtypes

Season                  str
Age                   int64
Squad                   str
Country                 str
Comp                    str
90s                 float64
Gls                   int64
Sh                  float64
SoT                 float64
SoT%                float64
Sh_90               float64
SoT_90              float64
G_Sh                float64
G_SoT               float64
PK                    int64
PKatt                 int64
Competition_Type        str
LgRank                  str
dtype: object

In [18]:
numeric_cols = [
    "Age", "MP", "Starts", "Min", "90s",
    "Gls", "Ast", "G+A", "G-PK", "PK", "PKatt",
    "CrdY", "CrdR",
    "Gls_90", "Ast_90", "G+A_90",
    "G-PK_90", "G+A-PK_90"
]

standard_stats[numeric_cols] = standard_stats[numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [19]:
shooting_numeric_cols = [
    "Age", "90s", "Gls", "Sh", "SoT",
    "SoT%", "Sh_90", "SoT_90",
    "G_Sh", "G_SoT", "PK", "PKatt"
]

shooting[shooting_numeric_cols] = shooting[shooting_numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [20]:
keys = ["Season", "Squad", "Comp", "Competition_Type"]

standard_stats.duplicated(keys).sum()

np.int64(6)

In [23]:
standard_stats.duplicated().sum()

np.int64(6)

In [24]:
all_copies = standard_stats[standard_stats.duplicated(keep=False)]
all_copies

,Season,Age,Squad,Country,Comp,LgRank,MP,Starts,Min,90s,...,PK,PKatt,CrdY,CrdR,Gls_90,Ast_90,G+A_90,G-PK_90,G+A-PK_90,Competition_Type
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,International Cup

In [27]:
standard_stats.dropna(inplace=True)

In [28]:
standard_stats.duplicated(keys).sum()

np.int64(0)

In [29]:
shooting.duplicated(keys).sum()

np.int64(0)

In [34]:
player_stats = standard_stats.merge(
    shooting,
    on=["Season", "Squad", "Comp", "Competition_Type"],
    how="left",
    suffixes=("", "_shooting")
)

### Start percentage

In [35]:
standard_stats["Start_Rate"] = (
    standard_stats["Starts"] / standard_stats["MP"]
)

### Minutes per match

In [36]:
standard_stats["Minutes_per_Match"] = (
    standard_stats["Min"] / standard_stats["MP"]
)

### Penalty conversion

In [37]:
standard_stats["Penalty_Conversion"] = (
    standard_stats["PK"] /
    standard_stats["PKatt"].replace(0, pd.NA)
)

# Career Overview

## Basic career information

In [38]:
standard_stats[
    ["Season", "Age", "Squad", "Comp", "Competition_Type", "Min"]
].sort_values("Season")

,Season,Age,Squad,Comp,Competition_Type,Min
0,2019-2020,16.0,Birmingham City,2. Championship,Club,2694.0
8,2019-2020,16.0,Birmingham City,2. Championship,Domestic League,2694.0
17,2019-2020,16.0,Birmingham City,FA Cup,Domestic Cup,152.0
16,2019-2020,16.0,Birmingham City,EFL Cup,Domestic Cup,80.0
46,2020,16.0,England,Friendlies (M),National Team,18.0
...,...,...,...,...,...,...
41,NaN,NaN,NaN,NaN,International Cup,NaN
42,NaN,NaN,NaN,NaN,International Cup,NaN
43,NaN,NaN,NaN,NaN,International Cup,NaN
44,NaN,NaN,NaN,NaN,International Cup,NaN
45,NaN,NaN,NaN,NaN,International Cup,NaN

## Age

In [39]:
min_age = standard_stats["Age"].min()
max_age = standard_stats["Age"].max()

print(f"Age range: {int(min_age)} - {int(max_age)}")

Age range: 16 - 23

In [40]:
age_by_season = (
    standard_stats[["Season", "Age"]]
    .drop_duplicates()
    .sort_values("Season")
)

age_by_season.dropna(subset=["Age"], inplace=True)

In [41]:
age_by_season

       Season   Age
0   2019-2020  16.0
46       2020  16.0
1   2020-2021  17.0
48       2021  17.0
2   2021-2022  18.0
50       2022  18.0
3   2022-2023  19.0
54       2023  20.0
4   2023-2024  20.0
55       2024  20.0
5   2024-2025  21.0
36       2025  21.0
6   2025-2026  22.0
59       2026  22.0
7   2026-2027  23.0

# Seasons

In [43]:
seasons = sorted(standard_stats["Season"].unique())

print("Number of seasons:", len(seasons))
print(seasons)

TypeError: '<' not supported between instances of 'float' and 'str'

In [44]:
career_timeline = (
    standard_stats[
        ["Season", "Age"]
    ]
    .drop_duplicates()
    .sort_values("Season")
)

career_timeline.dropna(subset=["Age"], inplace=True)

## Clubs

In [45]:
standard_stats["Squad"].unique()

<StringArray>
['Birmingham City', 'Dortmund', 'Real Madrid', nan, 'England']
Length: 5, dtype: str

In [46]:
clubs = standard_stats["Squad"].dropna().unique()

print("Number of clubs:", len(clubs))
print(clubs)

Number of clubs: 4
<StringArray>
['Birmingham City', 'Dortmund', 'Real Madrid', 'England']
Length: 4, dtype: str