In [67]:
import pandas as pd
import matplotlib.pyplot as plt

In [96]:
club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Club_Stats.csv")
domestic_league= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_leagues.csv")
domestic_cup= pd.read_csv(r"C:\Users\salma\Downloads\Domestic_cups.csv")
international_cups = pd.read_csv(r"C:\Users\salma\Downloads\International_cups.csv")
national_team = pd.read_csv(r"C:\Users\salma\Downloads\National_Team.csv")

#shooting

shooting_club_standard_stats = pd.read_csv(r"C:\Users\salma\Downloads\Shooting_Standard_Stats.csv")
shooting_domestic_league = pd.read_csv(r"C:\Users\salma\Downloads\League_Shooting_Standard_Stats_and_Summary.csv")
shooting_domestic_cup = pd.read_csv(r"C:\Users\salma\Downloads\Domestic_Cups_Shooting_Standard_Stats_and_Summary.csv")
shooting_international_cups = pd.read_csv(r"C:\Users\salma\Downloads\European_International_Cups_Shooting_Standard_Stats.csv")
shooting_national_team = pd.read_csv(r"C:\Users\salma\Downloads\International_England_Shooting_Standard_Stats.csv")

In [97]:
international_cups.dropna(inplace=True)

In [98]:
national_team = national_team.rename(columns={'Squad': 'Country'})

In [99]:
national_team

,Season,Age,Country,Comp,LgRank,MP,Starts,Min,90s,Gls,...,G-PK,PK,PKatt,CrdY,CrdR,Gls_90,Ast_90,G+A_90,G-PK_90,G+A-PK_90
0,2020,16,England,Friendlies (M),NaN,1,0,18.0,0.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
1,2020-2021,17,England,UEFA Nations League,LgA,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,17,England,Friendlies (M),NaN,2,1,116.0,1.3,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
3,2021,17,England,UEFA Euro,F,3,0,58.0,0.6,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
4,2022,18,England,1. World Cup,QF,5,5,414.0,4.6,1.0,...,1.0,0.0,0.0,1.0,0.0,0.22,0.22,0.43,0.22,0.43
5,2022,18,England,WCQ,NaN,4,2,224.0,2.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
6,2022,18,England,Friendlies (M),NaN,2,1,101.0,1.1,0.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
7,2022-2023,19,England,UEFA Nations League,LgA,5,4,413.0,4.6,0.0,...,0.0,0.0,0.0,1.0,0.0,0.00,0.00,0.00,0.00,0.00
8,2023,20,England,Friendlies (M),NaN,2,2,156.0,1.7,1.0,...,1.0,0.0,0.0,0.0,0.0,1.08,1.08,2.17,1.08,2.17
9,2024,20,England,UEFA Euro,2nd,7,7,670.0,7.4,2.0,...,1.0,0.0,0.0,2.0,0.0,0.27,0.13,0.40,0.27,0.40
10,2024,20,England,UEFA Euro qual.,NaN,4,4,316.0,3.5,1.0,...,1.0,0.0,0.0,1.0,0.0,0.28,0.28,0.56,0.28,0.56
11,2024-2025,21,England,UEFA Nations League,LgB,4,4,349.0,3.9,1.0,...,1.0,0.0,0.0,2.0,0.0,0.26,0.52,0.77,0.26,0.77
12,2025,21,England,Friendlies (M),NaN,1,0,20.0,0.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00
13,2026,22,England,1. World Cup,3rd,8,7,614.0,6.8,7.0,...,7.0,0.0,0.0,1.0,0.0,1.03,0.15,1.17,1.03,1.17
14,2026,22,England,WCQ,NaN,5,4,354.0,3.9,0.0,...,0.0,0.0,0.0,2.0,0.0,0.00,0.25,0.25,0.00,0.25
15,2026,22,England,Friendlies (M),NaN,2,1,110.0,1.2,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.00

In [100]:
club_standard_stats = club_standard_stats.copy()
domestic_league = domestic_league.copy()
domestic_cup = domestic_cup.copy()
international_cups = international_cups.copy()
national_team = national_team.copy()

club_standard_stats["Competition_Type"] = "Club"
domestic_league["Competition_Type"] = "Domestic League"
domestic_cup["Competition_Type"] = "Domestic Cup"
international_cups["Competition_Type"] = "International Cup"
national_team["Competition_Type"] = "National Team"

In [101]:
shooting_club_standard_stats["Competition_Type"] = "Club"
shooting_domestic_league["Competition_Type"] = "Domestic League"
shooting_domestic_cup["Competition_Type"] = "Domestic Cup"
shooting_international_cups["Competition_Type"] = "International Cup"
shooting_national_team["Competition_Type"] = "National Team"

In [102]:
standard_stats = pd.concat(
    [
        club_standard_stats,
        domestic_league,
        domestic_cup,
        international_cups,
        national_team
    ],
    ignore_index=True
)

In [103]:
standard_stats.shape

(55, 24)

In [104]:
standard_stats.head(5)

,Season,Age,Squad,Country,Comp,LgRank,MP,Starts,Min,90s,...,PK,PKatt,CrdY,CrdR,Gls_90,Ast_90,G+A_90,G-PK_90,G+A-PK_90,Competition_Type
0,2019-2020,16.0,Birmingham City,ENG,2. Championship,20th,41.0,32.0,2694.0,29.9,...,0.0,0.0,7.0,0.0,0.13,0.07,0.20,0.13,0.20,Club
1,2020-2021,17.0,Dortmund,GER,1. Bundesliga,3rd,29.0,19.0,1697.0,18.9,...,0.0,0.0,6.0,1.0,0.05,0.16,0.21,0.05,0.21,Club
2,2021-2022,18.0,Dortmund,GER,1. Bundesliga,2nd,32.0,32.0,2790.0,31.0,...,0.0,0.0,9.0,0.0,0.10,0.26,0.35,0.10,0.35,Club
3,2022-2023,19.0,Dortmund,GER,1. Bundesliga,2nd,31.0,30.0,2691.0,29.9,...,1.0,0.0,8.0,1.0,0.27,0.13,0.40,0.23,0.37,Club
4,2023-2024,20.0,Real Madrid,ESP,1. La Liga,1st,28.0,27.0,2315.0,25.7,...,1.0,1.0,5.0,1.0,0.74,0.23,0.97,0.70,0.93,Club

In [105]:
shooting = pd.concat(
    [
        shooting_club_standard_stats,
        shooting_domestic_league,
        shooting_domestic_cup,
        shooting_international_cups,
        shooting_national_team
    ],
    ignore_index=True
)

In [106]:
shooting.shape

(78, 18)

In [107]:
shooting["Competition_Type"].value_counts()

Competition_Type
Club                 31
National Team        16
Domestic Cup         13
International Cup    10
Domestic League       8
Name: count, dtype: int64

In [108]:
standard_stats[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

       Season            Squad                 Comp   Competition_Type
0   2019-2020  Birmingham City      2. Championship               Club
16  2019-2020  Birmingham City              EFL Cup       Domestic Cup
17  2019-2020  Birmingham City               FA Cup       Domestic Cup
8   2019-2020  Birmingham City      2. Championship    Domestic League
39       2020              NaN       Friendlies (M)      National Team
1   2020-2021         Dortmund        1. Bundesliga               Club
18  2020-2021         Dortmund            DFB-Pokal       Domestic Cup
19  2020-2021         Dortmund         DFL-Supercup       Domestic Cup
9   2020-2021         Dortmund        1. Bundesliga    Domestic League
29  2020-2021         Dortmund      1. Champions Lg  International Cup
40  2020-2021              NaN  UEFA Nations League      National Team
41       2021              NaN       Friendlies (M)      National Team
42       2021              NaN            UEFA Euro      National Team
2   2021-2022         Dortmund        1. Bundesliga               Club
20  2021-2022         Dortmund            DFB-Pokal       Domestic Cup
21  2021-2022         Dortmund         DFL-Supercup       Domestic Cup
10  2021-2022         Dortmund        1. Bundesliga    Domestic League
30  2021-2022         Dortmund      1. Champions Lg  International Cup
31  2021-2022         Dortmund         2. Europa Lg  International Cup
43       2022              NaN         1. World Cup      National Team
44       2022              NaN                  WCQ      National Team
45       2022              NaN       Friendlies (M)      National Team
3   2022-2023         Dortmund        1. Bundesliga               Club
22  2022-2023         Dortmund            DFB-Pokal       Domestic Cup
11  2022-2023         Dortmund        1. Bundesliga    Domestic League
32  2022-2023         Dortmund      1. Champions Lg  International Cup
46  2022-2023              NaN  UEFA Nations League      National Team
47       2023              NaN       Friendlies (M)      National Team
4   2023-2024      Real Madrid           1. La Liga               Club
23  2023-2024      Real Madrid         Copa del Rey       Domestic Cup
24  2023-2024      Real Madrid  Supercopa de España       Domestic Cup
12  2023-2024      Real Madrid           1. La Liga    Domestic League
33  2023-2024      Real Madrid      1. Champions Lg  International Cup
48       2024              NaN            UEFA Euro      National Team
49       2024              NaN      UEFA Euro qual.      National Team
5   2024-2025      Real Madrid           1. La Liga               Club
25  2024-2025      Real Madrid         Copa del Rey       Domestic Cup
26  2024-2025      Real Madrid  Supercopa de España       Domestic Cup
13  2024-2025      Real Madrid           1. La Liga    Domestic League
34  2024-2025      Real Madrid      1. Champions Lg  International Cup
35  2024-2025      Real Madrid            Super Cup  International Cup
50  2024-2025              NaN  UEFA Nations League      National Team
36       2025      Real Madrid    1. Club World Cup  International Cup
51       2025              NaN       Friendlies (M)      National Team
6   2025-2026      Real Madrid           1. La Liga               Club
27  2025-2026      Real Madrid         Copa del Rey       Domestic Cup
28  2025-2026      Real Madrid  Supercopa de España       Domestic Cup
14  2025-2026      Real Madrid           1. La Liga    Domestic League
37  2025-2026      Real Madrid      1. Champions Lg  International Cup
52       2026              NaN         1. World Cup      National Team
53       2026              NaN                  WCQ      National Team
54       2026              NaN       Friendlies (M)      National Team
7   2026-2027      Real Madrid           1. La Liga               Club
15  2026-2027      Real Madrid           1. La Liga    Domestic League
38  2026-2027      Real Madrid      1. Champions Lg  International Cup

In [109]:
shooting[
    ["Season", "Squad", "Comp", "Competition_Type"]
].sort_values(["Season", "Competition_Type"])

       Season            Squad             Comp   Competition_Type
0   2019-2020  Birmingham City  2. Championship               Club
1   2019-2020  Birmingham City          EFL Cup               Club
2   2019-2020  Birmingham City           FA Cup               Club
39  2019-2020  Birmingham City          EFL Cup       Domestic Cup
40  2019-2020  Birmingham City           FA Cup       Domestic Cup
..        ...              ...              ...                ...
77       2026          England   Friendlies (M)      National Team
29  2026-2027      Real Madrid  1. Champions Lg               Club
30  2026-2027      Real Madrid       1. La Liga               Club
38  2026-2027      Real Madrid       1. La Liga    Domestic League
61  2026-2027      Real Madrid  1. Champions Lg  International Cup

[78 rows x 4 columns]

In [110]:
standard_stats.groupby(
    ["Season", "Competition_Type"]
).size()

Season     Competition_Type
2019-2020  Club                 1
           Domestic Cup         2
           Domestic League      1
2020       National Team        1
2020-2021  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
           National Team        1
2021       National Team        2
2021-2022  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    2
2022       National Team        3
2022-2023  Club                 1
           Domestic Cup         1
           Domestic League      1
           International Cup    1
           National Team        1
2023       National Team        1
2023-2024  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2024       National Team        2
2024-2025  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    2
           National Team        1
2025       International Cup    1
           National Team        1
2025-2026  Club                 1
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2026       National Team        3
2026-2027  Club                 1
           Domestic League      1
           International Cup    1
dtype: int64

In [111]:
shooting.groupby(
    ["Season", "Competition_Type"]
).size()

Season     Competition_Type
2019-2020  Club                 3
           Domestic Cup         2
           Domestic League      1
2020       National Team        1
2020-2021  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2021       National Team        2
2021-2022  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
2022       National Team        3
2022-2023  Club                 3
           Domestic Cup         1
           Domestic League      1
           International Cup    1
           National Team        1
2023       National Team        1
2023-2024  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2024       National Team        3
2024-2025  Club                 5
           Domestic Cup         2
           Domestic League      1
           International Cup    2
           National Team        1
2025       Club                 1
           International Cup    1
           National Team        1
2025-2026  Club                 4
           Domestic Cup         2
           Domestic League      1
           International Cup    1
2026       National Team        3
2026-2027  Club                 2
           Domestic League      1
           International Cup    1
dtype: int64

In [112]:
standard_stats.isna().sum()

Season               0
Age                  0
Squad               16
Country             10
Comp                 0
LgRank              10
MP                   0
Starts               0
Min                  1
90s                  1
Gls                  1
Ast                  1
G+A                  1
G-PK                 1
PK                   1
PKatt                1
CrdY                 1
CrdR                 1
Gls_90               1
Ast_90               1
G+A_90               1
G-PK_90              1
G+A-PK_90            1
Competition_Type     0
dtype: int64

In [113]:
standard_stats.dtypes

Season                  str
Age                 float64
Squad                   str
Country                 str
Comp                    str
LgRank                  str
MP                  float64
Starts              float64
Min                 float64
90s                 float64
Gls                  object
Ast                 float64
G+A                 float64
G-PK                float64
PK                  float64
PKatt               float64
CrdY                float64
CrdR                float64
Gls_90              float64
Ast_90              float64
G+A_90              float64
G-PK_90             float64
G+A-PK_90           float64
Competition_Type        str
dtype: object

In [114]:
shooting.dtypes

Season                  str
Age                   int64
Squad                   str
Country                 str
Comp                    str
90s                 float64
Gls                   int64
Sh                  float64
SoT                 float64
SoT%                float64
Sh_90               float64
SoT_90              float64
G_Sh                float64
G_SoT               float64
PK                    int64
PKatt                 int64
Competition_Type        str
LgRank                  str
dtype: object

In [115]:
numeric_cols = [
    "Age", "MP", "Starts", "Min", "90s",
    "Gls", "Ast", "G+A", "G-PK", "PK", "PKatt",
    "CrdY", "CrdR",
    "Gls_90", "Ast_90", "G+A_90",
    "G-PK_90", "G+A-PK_90"
]

standard_stats[numeric_cols] = standard_stats[numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [116]:
shooting_numeric_cols = [
    "Age", "90s", "Gls", "Sh", "SoT",
    "SoT%", "Sh_90", "SoT_90",
    "G_Sh", "G_SoT", "PK", "PKatt"
]

shooting[shooting_numeric_cols] = shooting[shooting_numeric_cols].apply(
    pd.to_numeric,
    errors="coerce"
)

In [117]:
keys = ["Season", "Squad", "Comp", "Competition_Type"]

standard_stats.duplicated(keys).sum()

np.int64(0)

In [119]:
shooting.duplicated(keys).sum()

np.int64(0)

In [120]:
player_stats = standard_stats.merge(
    shooting,
    on=["Season", "Squad", "Comp", "Competition_Type"],
    how="left",
    suffixes=("", "_shooting")
)

### Start percentage

In [121]:
standard_stats["Start_Rate"] = (
    standard_stats["Starts"] / standard_stats["MP"]
)

### Minutes per match

In [122]:
standard_stats["Minutes_per_Match"] = (
    standard_stats["Min"] / standard_stats["MP"]
)

### Penalty conversion

In [123]:
standard_stats["Penalty_Conversion"] = (
    standard_stats["PK"] /
    standard_stats["PKatt"].replace(0, pd.NA)
)

# Career Overview

## Basic career information

In [124]:
standard_stats[
    ["Season", "Age", "Squad", "Comp", "Competition_Type", "Min"]
].sort_values("Season")

,Season,Age,Squad,Comp,Competition_Type,Min
0,2019-2020,16.0,Birmingham City,2. Championship,Club,2694.0
8,2019-2020,16.0,Birmingham City,2. Championship,Domestic League,2694.0
17,2019-2020,16.0,Birmingham City,FA Cup,Domestic Cup,152.0
16,2019-2020,16.0,Birmingham City,EFL Cup,Domestic Cup,80.0
39,2020,16.0,NaN,Friendlies (M),National Team,18.0
1,2020-2021,17.0,Dortmund,1. Bundesliga,Club,1697.0
40,2020-2021,17.0,NaN,UEFA Nations League,National Team,NaN
29,2020-2021,17.0,Dortmund,1. Champions Lg,International Cup,687.0
9,2020-2021,17.0,Dortmund,1. Bundesliga,Domestic League,1697.0
19,2020-2021,17.0,Dortmund,DFL-Supercup,Domestic Cup,15.0
18,2020-2021,17.0,Dortmund,DFB-Pokal,Domestic Cup,417.0
41,2021,17.0,NaN,Friendlies (M),National Team,116.0
42,2021,17.0,NaN,UEFA Euro,National Team,58.0
31,2021-2022,18.0,Dortmund,2. Europa Lg,International Cup,180.0
30,2021-2022,18.0,Dortmund,1. Champions Lg,International Cup,500.0
20,2021-2022,18.0,Dortmund,DFB-Pokal,Domestic Cup,234.0
21,2021-2022,18.0,Dortmund,DFL-Supercup,Domestic Cup,83.0
2,2021-2022,18.0,Dortmund,1. Bundesliga,Club,2790.0
10,2021-2022,18.0,Dortmund,1. Bundesliga,Domestic League,2790.0
43,2022,18.0,NaN,1. World Cup,National Team,414.0
44,2022,18.0,NaN,WCQ,National Team,224.0
45,2022,18.0,NaN,Friendlies (M),National Team,101.0
11,2022-2023,19.0,Dortmund,1. Bundesliga,Domestic League,2691.0
22,2022-2023,19.0,Dortmund,DFB-Pokal,Domestic Cup,237.0
3,2022-2023,19.0,Dortmund,1. Bundesliga,Club,2691.0
46,2022-2023,19.0,NaN,UEFA Nations League,National Team,413.0
32,2022-2023,19.0,Dortmund,1. Champions Lg,International Cup,630.0
47,2023,20.0,NaN,Friendlies (M),National Team,156.0
12,2023-2024,20.0,Real Madrid,1. La Liga,Domestic League,2315.0
23,2023-2024,20.0,Real Madrid,Copa del Rey,Domestic Cup,120.0
24,2023-2024,20.0,Real Madrid,Supercopa de España,Domestic Cup,205.0
4,2023-2024,20.0,Real Madrid,1. La Liga,Club,2315.0
33,2023-2024,20.0,Real Madrid,1. Champions Lg,International Cup,989.0
49,2024,20.0,NaN,UEFA Euro qual.,National Team,316.0
48,2024,20.0,NaN,UEFA Euro,National Team,670.0
34,2024-2025,21.0,Real Madrid,1. Champions Lg,International Cup,1131.0
35,2024-2025,21.0,Real Madrid,Super Cup,International Cup,88.0
50,2024-2025,21.0,NaN,UEFA Nations League,National Team,349.0
26,2024-2025,21.0,Real Madrid,Supercopa de España,Domestic Cup,180.0
25,2024-2025,21.0,Real Madrid,Copa del Rey,Domestic Cup,360.0
13,2024-2025,21.0,Real Madrid,1. La Liga,Domestic League,2488.0
5,2024-2025,21.0,Real Madrid,1. La Liga,Club,2488.0
36,2025,21.0,Real Madrid,1. Club World Cup,International Cup,442.0
51,2025,21.0,NaN,Friendlies (M),National Team,20.0
27,2025-2026,22.0,Real Madrid,Copa del Rey,Domestic Cup,14.0
37,2025-2026,22.0,Real Madrid,1. Champions Lg,International Cup,610.0
28,2025-2026,22.0,Real Madrid,Supercopa de España,Domestic Cup,180.0
14,2025-2026,22.0,Real Madrid,1. La Liga,Domestic League,1916.0
6,2025-2026,22.0,Real Madrid,1. La Liga,Club,1916.0
53,2026,22.0,NaN,WCQ,National Team,354.0
52,2026,22.0,NaN,1. World Cup,National Team,614.0
54,2026,22.0,NaN,Friendlies (M),National Team,110.0
15,2026-2027,23.0,Real Madrid,1. La Liga,Domestic League,422.0
7,2026-2027,23.0,Real Madrid,1. La Liga,Club,422.0
38,2026-2027,23.0,Real Madrid,1. Champions Lg,International Cup,90.0

## Age

In [125]:
min_age = standard_stats["Age"].min()
max_age = standard_stats["Age"].max()

print(f"Age range: {int(min_age)} - {int(max_age)}")

Age range: 16 - 23

In [126]:
age_by_season = (
    standard_stats[["Season", "Age"]]
    .drop_duplicates()
    .sort_values("Season")
)

age_by_season.dropna(subset=["Age"], inplace=True)

In [127]:
age_by_season

       Season   Age
0   2019-2020  16.0
39       2020  16.0
1   2020-2021  17.0
41       2021  17.0
2   2021-2022  18.0
43       2022  18.0
3   2022-2023  19.0
47       2023  20.0
4   2023-2024  20.0
48       2024  20.0
5   2024-2025  21.0
36       2025  21.0
6   2025-2026  22.0
52       2026  22.0
7   2026-2027  23.0

# Seasons

In [128]:
seasons = sorted(standard_stats["Season"].unique())

print("Number of seasons:", len(seasons))
print(seasons)

Number of seasons: 15
['2019-2020', '2020', '2020-2021', '2021', '2021-2022', '2022', '2022-2023', '2023', '2023-2024', '2024', '2024-2025', '2025', '2025-2026', '2026', '2026-2027']

In [129]:
career_timeline = (
    standard_stats[
        ["Season", "Age"]
    ]
    .drop_duplicates()
    .sort_values("Season")
)

career_timeline.dropna(subset=["Age"], inplace=True)

## Clubs

In [133]:
clubs = standard_stats["Squad"].dropna().unique()

print("Number of clubs:", len(clubs))
print(clubs)

Number of clubs: 3
<StringArray>
['Birmingham City', 'Dortmund', 'Real Madrid']
Length: 3, dtype: str

## Competitions

In [135]:
standard_stats["Competition_Type"].value_counts()

Competition_Type
National Team        16
Domestic Cup         13
International Cup    10
Club                  8
Domestic League       8
Name: count, dtype: int64

In [136]:
competitions = (
    standard_stats["Comp"]
    .dropna()
    .unique()
)

print(competitions)

<StringArray>
[    '2. Championship',       '1. Bundesliga',          '1. La Liga',
             'EFL Cup',              'FA Cup',           'DFB-Pokal',
        'DFL-Supercup',        'Copa del Rey', 'Supercopa de España',
     '1. Champions Lg',        '2. Europa Lg',           'Super Cup',
   '1. Club World Cup',      'Friendlies (M)', 'UEFA Nations League',
           'UEFA Euro',        '1. World Cup',                 'WCQ',
     'UEFA Euro qual.']
Length: 19, dtype: str

In [137]:
competition_summary = (
    standard_stats
    .groupby("Competition_Type")["Comp"]
    .nunique()
    .reset_index(name="Number_of_Competitions")
)

competition_summary

    Competition_Type  Number_of_Competitions
0               Club                       3
1       Domestic Cup                       6
2    Domestic League                       3
3  International Cup                       4
4      National Team                       6

## Minutes